### ISSUE TITLE
[bug] crash when applying a theme with -t

### ISSUE THREAD

**Issue by binarykitchen** [tyler-johnson/bootstrap-package-manager#2]
hello there

just spotted this. maybe you can fix?

```
> bpm -t Spacelab

Initiating...

Downloading Bootstrap...
[=============================================    ] 92% 0.1s
Unpacking Bootstrap...

Installing Bootswatch Theme 'Spacelab'...


BPM crashed with the following error:

Error: Bootswatch Theme spacelab couldn't be found.
    at Request._callback (/opt/node-0.10.11/lib/node_modules/bootstrap-package-manager/lib/bootswatch.js:41:21)
    at Request.self.callback (/opt/node-0.10.11/lib/node_modules/bootstrap-package-manager/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/opt/node-0.10.11/lib/node_modules/bootstrap-package-manager/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/opt/node-0.10.11/lib/node_modules/bootstrap-package-manager/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
```

**Comment by upstroke** [comment]
Same error with theme yeti
